name: Build and deploy ASP.Net Core app to Azure Web App - webappganesha888

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Clean workspace
        run: git clean -xfd

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build entire solution
        run: dotnet build learningapp.sln --configuration Release

      - name: Publish only the main Web App project
        run: dotnet publish learningapp/learningapp.csproj --configuration Release --output ./publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE95199B581742D2A5D8A0F9D334EF93 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA4BD390B55C4006ACA36FFB0B8D816A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2D3C1B1161C4AC2949A9C17ED424CFF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappganesha888'
          slot-name: 'Production'
          package: .
